"""Command-line interface for the A/H relative-value workflow."""

from __future__ import annotations

import argparse
from datetime import date, datetime
from pathlib import Path
import sys
import tomllib

from .config import (
    DEFAULT_CACHE_DIR,
    DEFAULT_RUNS_DIR,
    CostConfig,
    DataConfig,
    PipelineConfig,
    RollingConfig,
    StrategyConfig,
)


def _config_pre_parser() -> argparse.ArgumentParser:
    """Parse `--config` early so TOML presets can seed the main argv."""

    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--config", type=Path, default=None)
    return parser


def build_parser() -> argparse.ArgumentParser:
    """Construct the CLI parser."""

    parser = argparse.ArgumentParser(description="Run an A/H relative-value analysis pipeline.")
    parser.add_argument(
        "--config",
        type=Path,
        default=None,
        help="Optional TOML preset. Explicit CLI flags override keys loaded from this file.",
    )
    parser.add_argument("--a-symbol", default="600036", help="A-share symbol used as the mainland leg.")
    parser.add_argument("--h-symbol", default="03968", help="H-share symbol used as the Hong Kong leg.")
    parser.add_argument(
        "--data-provider",
        default="akshare",
        choices=("akshare", "tushare", "simulated"),
        help="Market data provider. `simulated` needs no network or token for offline smoke runs.",
    )
    parser.add_argument(
        "--tushare-token",
        default=None,
        help="Tushare API token used when `--data-provider tushare` is selected. Falls back to TUSHARE_TOKEN.",
    )
    parser.add_argument(
        "--tushare-ts-code-a",
        default=None,
        help="Tushare ts_code for the A-share leg, for example 600036.SH.",
    )
    parser.add_argument(
        "--tushare-ts-code-h",
        default=None,
        help="Tushare ts_code for the H-share leg, for example 03968.HK.",
    )
    parser.add_argument(
        "--tushare-adjust",
        default="qfq",
        help="Adjustment used by the tushare provider, for example qfq or hfq.",
    )
    parser.add_argument(
        "--simulation-seed",
        type=int,
        default=7,
        help="Random seed for the `simulated` data provider.",
    )
    parser.add_argument(
        "--simulation-n-days",
        type=int,
        default=1500,
        help="Approximate number of business days generated by the `simulated` data provider.",
    )
    parser.add_argument(
        "--backtest-engine",
        default="trade",
        choices=("trade", "weight"),
        help="`trade` runs discrete position-based backtests. `weight` runs the rolling OU weight engine.",
    )
    parser.add_argument(
        "--mean-reversion-gate-mode",
        default="off",
        choices=("off", "half_life_range", "lb_filter", "both"),
        help="Optional quality gate on the rolling OU estimates for the trade engine.",
    )
    parser.add_argument(
        "--ou-window",
        type=int,
        default=252,
        help="Trailing window used by the rolling OU MLE estimator.",
    )
    parser.add_argument(
        "--ou-det-order",
        type=int,
        default=0,
        help="Deterministic-order argument passed to the Johansen estimator.",
    )
    parser.add_argument(
        "--ou-k-ar-diff",
        type=int,
        default=1,
        help="Differenced-lag order passed to the Johansen estimator.",
    )
    parser.add_argument(
        "--ou-lags",
        type=int,
        default=10,
        help="Lag order used by the Ljung-Box test on the OU innovations.",
    )
    parser.add_argument(
        "--half-life-min-days",
        type=float,
        default=5.0,
        help="Minimum OU half-life that keeps a signal tradeable.",
    )
    parser.add_argument(
        "--half-life-max-days",
        type=float,
        default=90.0,
        help="Maximum OU half-life that keeps a signal tradeable.",
    )
    parser.add_argument(
        "--lb-p-value-min",
        type=float,
        default=0.05,
        help="Minimum Ljung-Box p-value required for a tradeable signal.",
    )
    parser.add_argument(
        "--min-weight",
        type=float,
        default=0.10,
        help="Minimum weight kept on each leg in the weight engine's tilt band.",
    )
    parser.add_argument(
        "--position-sizing-mode",
        default="fixed",
        choices=("fixed", "vol_target"),
        help="`vol_target` scales positions toward a volatility target with a leverage cap.",
    )
    parser.add_argument(
        "--target-vol",
        type=float,
        default=0.10,
        help="Annualized volatility target used by vol-target position sizing.",
    )
    parser.add_argument(
        "--vol-window",
        type=int,
        default=60,
        help="Trailing window used to estimate portfolio volatility.",
    )
    parser.add_argument(
        "--vol-min-periods",
        type=int,
        default=None,
        help="Minimum observations before the volatility estimate is valid.",
    )
    parser.add_argument(
        "--max-leverage",
        type=float,
        default=2.0,
        help="Maximum gross leverage allowed by vol-target sizing.",
    )
    parser.add_argument(
        "--max-drawdown",
        type=float,
        default=0.10,
        help="Drawdown threshold that suspends trading for `--suspend-days` days. Set 0 to disable.",
    )
    parser.add_argument(
        "--suspend-days",
        type=int,
        default=20,
        help="Trading days to stay flat after a drawdown breaker triggers.",
    )
    parser.add_argument(
        "--portfolio-max-drawdown",
        type=float,
        default=0.18,
        help="Deeper drawdown threshold that flattens the portfolio permanently. Set 0 to disable.",
    )
    parser.add_argument(
        "--risk-free-rate",
        type=float,
        default=0.0,
        help="Annualized risk-free rate credited to cash inside the weight engine.",
    )
    parser.add_argument(
        "--base-cost-bps",
        type=float,
        default=3.0,
        help="Weight-engine base cost applied per unit of turnover, in bps.",
    )
    parser.add_argument(
        "--impact-cost-bps",
        type=float,
        default=2.0,
        help="Weight-engine impact cost coefficient on turnover times gross exposure, in bps.",
    )
    parser.add_argument("--benchmark", default=None, help="Optional benchmark symbol used for rolling beta.")
    parser.add_argument(
        "--benchmark-market",
        default="a",
        choices=("a", "h"),
        help="Market of the optional benchmark symbol.",
    )
    parser.add_argument(
        "--benchmark-mode",
        default="auto",
        choices=("auto", "external", "internal", "off"),
        help=(
            "How the reporting benchmark is resolved. "
            "`auto` prefers an explicit external benchmark and otherwise uses an internal A/H basket "
            "for `long_cheaper_leg_only`."
        ),
    )
    parser.add_argument(
        "--internal-benchmark-weighting",
        default="hedge_ratio",
        choices=("hedge_ratio", "equal_weight"),
        help="Weighting used when the internal passive A/H basket benchmark is enabled.",
    )
    parser.add_argument("--start-date", default="2018-01-01", help="Analysis start date in YYYY-MM-DD format.")
    parser.add_argument("--end-date", default="2024-12-31", help="Analysis end date in YYYY-MM-DD format.")
    parser.add_argument(
        "--train-end-date",
        default="2022-12-31",
        help="The last date included in the training sample.",
    )
    parser.add_argument(
        "--a-csv",
        type=Path,
        default=None,
        help="Optional user-supplied local CSV for the A-share history. When set, this exact file is used.",
    )
    parser.add_argument(
        "--h-csv",
        type=Path,
        default=None,
        help="Optional user-supplied local CSV for the H-share history. When set, this exact file is used.",
    )
    parser.add_argument(
        "--fx-csv",
        type=Path,
        default=None,
        help="Optional user-supplied local CSV for the HKD/CNY history. When set, this exact file is used.",
    )
    parser.add_argument(
        "--benchmark-csv",
        type=Path,
        default=None,
        help="Optional user-supplied local CSV for the benchmark history. When set, this exact file is used.",
    )
    parser.add_argument(
        "--constant-fx-rate",
        type=float,
        default=None,
        help="Fallback static HKD/CNY rate used when no FX history is provided.",
    )
    parser.add_argument("--share-ratio", type=float, default=1.0, help="Share-conversion ratio between A and H.")
    parser.add_argument(
        "--execution-mode",
        default="long_cheaper_leg_only",
        choices=("long_cheaper_leg_only", "paired"),
        help="Execution mode for the strategy.",
    )
    parser.add_argument(
        "--execution-timing",
        default="next_open",
        choices=("close", "next_open"),
        help="Execute on the same bar close or on the next bar open using lagged signals.",
    )
    parser.add_argument(
        "--entry-signal-mode",
        default="zscore",
        choices=("zscore", "ret_spread_ema", "ret_spread_sma"),
        help="Primary signal used for entry threshold search and trade management.",
    )
    parser.add_argument(
        "--hedge-ratio-mode",
        default="training",
        choices=("training", "rolling"),
        help="Use the training-sample hedge ratio or time-varying rolling estimates for spread construction and paired sizing.",
    )
    parser.add_argument("--z-window", type=int, default=120, help="Rolling window used to standardize the spread.")
    parser.add_argument(
        "--z-min-periods",
        type=int,
        default=60,
        help="Minimum observations required before a rolling z-score is considered valid.",
    )
    parser.add_argument(
        "--return-filter-mode",
        default="off",
        choices=("off", "ema", "sma"),
        help="Optional moving-average confirmation filter applied on the return spread.",
    )
    parser.add_argument(
        "--cointegration-gate-mode",
        default="off",
        choices=("off", "significant"),
        help="Optional rolling cointegration gate. `significant` only allows trades when the latest rolling p-value stays below alpha.",
    )
    parser.add_argument(
        "--ecm-gate-mode",
        default="off",
        choices=("off", "significant_negative"),
        help=(
            "Optional rolling ECM gate. `significant_negative` only allows trades when the latest error-correction "
            "speed is negative and statistically significant."
        ),
    )
    parser.add_argument(
        "--half-life-anchor-mode",
        default="off",
        choices=("off", "training"),
        help="Optionally anchor z-window and/or max holding days to the training-sample residual half-life.",
    )
    parser.add_argument(
        "--half-life-z-window-multiplier",
        type=float,
        default=None,
        help="If set with `--half-life-anchor-mode training`, derive z-window as round(training half-life * multiplier).",
    )
    parser.add_argument(
        "--half-life-max-holding-multiplier",
        type=float,
        default=None,
        help=(
            "If set with `--half-life-anchor-mode training`, derive max holding days as "
            "round(training half-life * multiplier)."
        ),
    )
    parser.add_argument(
        "--return-filter-window",
        type=int,
        default=10,
        help="Window used to build the return-spread EMA/SMA signals.",
    )
    parser.add_argument(
        "--return-filter-min-periods",
        type=int,
        default=None,
        help="Minimum observations required before the return-spread filter is considered valid.",
    )
    parser.add_argument(
        "--z-grid",
        default="1.5,2.0,2.5",
        help="Comma-separated entry z-score candidates used in the training grid search.",
    )
    parser.add_argument("--exit-z", type=float, default=0.5, help="Exit z-score threshold.")
    parser.add_argument("--stop-z", type=float, default=3.0, help="Stop-loss z-score threshold.")
    parser.add_argument(
        "--max-holding-days",
        type=int,
        default=15,
        help="Maximum holding period per trade in trading days.",
    )
    parser.add_argument(
        "--position-size-fraction",
        type=float,
        default=0.95,
        help="Fraction of current capital allocated to a new position.",
    )
    parser.add_argument(
        "--adv-window",
        type=int,
        default=20,
        help="Trailing window used to estimate average daily volume for capacity and impact controls.",
    )
    parser.add_argument(
        "--adv-min-periods",
        type=int,
        default=None,
        help="Minimum observations required before ADV-based controls are considered valid.",
    )
    parser.add_argument(
        "--max-adv-fraction",
        type=float,
        default=0.05,
        help="Maximum fraction of trailing ADV allowed per trade leg. Set a negative value to disable the cap.",
    )
    parser.add_argument("--a-lot-size", type=int, default=100, help="Lot size used for the A-share leg.")
    parser.add_argument("--h-lot-size", type=int, default=100, help="Lot size used for the H-share leg.")
    parser.add_argument("--initial-capital", type=float, default=100000.0, help="Initial capital for backtests.")
    parser.add_argument(
        "--objective",
        default="sharpe_ratio",
        choices=(
            "sharpe_ratio",
            "annual_return",
            "final_capital",
            "total_return",
            "win_rate",
        ),
        help="Metric used to select the best entry z-score on the training sample.",
    )
    parser.add_argument("--a-buy-cost-bps", type=float, default=2.0, help="A-share buy-side cost in bps.")
    parser.add_argument("--a-sell-cost-bps", type=float, default=2.0, help="A-share sell-side cost in bps.")
    parser.add_argument("--h-buy-cost-bps", type=float, default=8.0, help="H-share buy-side base cost in bps.")
    parser.add_argument("--h-sell-cost-bps", type=float, default=8.0, help="H-share sell-side base cost in bps.")
    parser.add_argument(
        "--h-stamp-duty-bps",
        type=float,
        default=10.0,
        help="Explicit H-share stamp duty assumption in bps.",
    )
    parser.add_argument(
        "--fx-conversion-bps",
        type=float,
        default=2.0,
        help="Implicit FX conversion cost applied to H-share trades in bps.",
    )
    parser.add_argument("--a-slippage-bps", type=float, default=3.0, help="Base one-way A-share slippage in bps.")
    parser.add_argument("--h-slippage-bps", type=float, default=6.0, help="Base one-way H-share slippage in bps.")
    parser.add_argument(
        "--a-impact-bps-per-100pct-adv",
        type=float,
        default=15.0,
        help="Additional A-share slippage in bps when the order equals 100%% of trailing ADV.",
    )
    parser.add_argument(
        "--h-impact-bps-per-100pct-adv",
        type=float,
        default=25.0,
        help="Additional H-share slippage in bps when the order equals 100%% of trailing ADV.",
    )
    parser.add_argument(
        "--a-short-borrow-apr-bps",
        type=float,
        default=250.0,
        help="Annualized A-share borrow fee applied to short notional in paired mode, in bps.",
    )
    parser.add_argument(
        "--h-short-borrow-apr-bps",
        type=float,
        default=150.0,
        help="Annualized H-share borrow fee applied to short notional in paired mode, in bps.",
    )
    parser.add_argument(
        "--a-long-financing-apr-bps",
        type=float,
        default=0.0,
        help="Annualized financing drag applied to A-share long notional while positions are open, in bps.",
    )
    parser.add_argument(
        "--h-long-financing-apr-bps",
        type=float,
        default=0.0,
        help="Annualized financing drag applied to H-share long notional while positions are open, in bps.",
    )
    parser.add_argument(
        "--allow-non-coint",
        action="store_true",
        help="Allow the pipeline to continue even if training-sample cointegration is not significant.",
    )
    parser.add_argument(
        "--same-issuer-check",
        default="strict",
        choices=("strict", "warn", "off"),
        help=(
            "Validate the A/H symbols against the built-in same-issuer registry. "
            "`strict` rejects known mismatches such as 601857/00883."
        ),
    )
    parser.add_argument(
        "--cache-dir",
        type=Path,
        default=DEFAULT_CACHE_DIR,
        help="Directory used for automatic data caching and optional stage checkpoints.",
    )
    parser.add_argument(
        "--no-cache",
        action="store_true",
        help="Disable all disk-backed caching for this run.",
    )
    parser.add_argument(
        "--refresh-cache",
        action="store_true",
        help="Rebuild market-data master histories from fresh downloads and ignore existing stage-cache entries for this run.",
    )
    parser.add_argument(
        "--resume-from-cache",
        action="store_true",
        help="Reuse cached pipeline stages only; the market-data cache still uses its default automatic incremental symbol-history behavior.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help=f"Optional directory used to save CSV, JSON, text, and PNG artifacts. Recommended under `{DEFAULT_RUNS_DIR}/<run-name>`.",
    )
    return parser


def _load_config_payload(path: Path) -> dict[str, object]:
    """Load a flat TOML config file for CLI-style overrides."""

    try:
        with path.open("rb") as handle:
            payload = tomllib.load(handle)
    except FileNotFoundError as exc:
        raise ValueError(f"Config file `{path}` does not exist.") from exc
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"Config file `{path}` is not valid TOML: {exc}") from exc

    if not isinstance(payload, dict):
        raise ValueError(f"Config file `{path}` must contain a top-level TOML table.")
    return payload


def _serialize_config_scalar(value: object) -> str:
    """Convert supported TOML scalar values into CLI token strings."""

    if isinstance(value, Path):
        return str(value)
    if isinstance(value, datetime):
        return value.strftime("%Y-%m-%dT%H:%M:%S")
    if isinstance(value, date):
        return value.strftime("%Y-%m-%d")
    return str(value)


def _resolve_config_path_value(config_path: Path, value: object) -> Path:
    """Resolve TOML path-like values relative to the config file location."""

    raw_path = Path(str(value))
    if raw_path.is_absolute():
        return raw_path
    return (config_path.parent / raw_path).resolve()


def _config_tokens_from_payload(parser: argparse.ArgumentParser, path: Path) -> list[str]:
    """Convert flat TOML entries into CLI tokens so argparse validates them."""

    payload = _load_config_payload(path)
    actions_by_dest = {
        action.dest: action
        for action in parser._actions
        if action.option_strings and action.dest not in {"help", "config"}
    }

    tokens: list[str] = []
    unknown_keys: list[str] = []

    for key, value in payload.items():
        action = actions_by_dest.get(key)
        if action is None:
            unknown_keys.append(key)
            continue
        if isinstance(value, dict):
            raise ValueError(
                f"Config file `{path}` uses a nested table for `{key}`. "
                "Use flat top-level keys that match CLI flag names."
            )

        option = action.option_strings[0]
        is_store_true = (
            action.nargs == 0
            and getattr(action, "const", None) is True
            and bool(getattr(action, "default", False)) is False
        )
        if is_store_true:
            if not isinstance(value, bool):
                raise ValueError(f"Config key `{key}` in `{path}` must be a boolean.")
            if value:
                tokens.append(option)
            continue

        if key == "z_grid":
            if isinstance(value, (list, tuple)):
                tokens.extend((option, ",".join(_serialize_config_scalar(item) for item in value)))
                continue
            tokens.extend((option, _serialize_config_scalar(value)))
            continue
        if isinstance(value, (list, tuple)):
            raise ValueError(
                f"Config key `{key}` in `{path}` must be a scalar value. "
                "Only `z_grid` currently accepts an array."
            )
        if action.type is Path:
            tokens.extend((option, str(_resolve_config_path_value(path, value))))
            continue

        tokens.extend((option, _serialize_config_scalar(value)))

    if unknown_keys:
        supported = ", ".join(sorted(actions_by_dest))
        raise ValueError(
            f"Config file `{path}` contains unsupported keys: {', '.join(sorted(unknown_keys))}. "
            f"Supported keys match CLI destinations: {supported}."
        )
    return tokens


def _merge_config_argv(parser: argparse.ArgumentParser, argv: list[str]) -> list[str]:
    """Merge built-in defaults, TOML overrides, and explicit CLI flags."""

    config_path = _config_pre_parser().parse_known_args(argv)[0].config
    if config_path is None:
        return argv
    return _config_tokens_from_payload(parser, config_path) + argv


def _parse_z_grid(raw_value: str) -> tuple[float, ...]:
    """Parse the CLI/config z-grid into a validated numeric tuple."""

    grid = tuple(float(value.strip()) for value in raw_value.split(",") if value.strip())
    if not grid:
        raise ValueError("`--z-grid` must contain at least one numeric threshold.")
    return grid


def main(argv: list[str] | None = None) -> int:
    """Parse arguments, run the pipeline, and print a concise summary."""

    raw_argv = list(argv) if argv is not None else sys.argv[1:]
    parser = build_parser()
    args = parser.parse_args(_merge_config_argv(parser, raw_argv))
    z_grid = _parse_z_grid(args.z_grid)

    from .pipeline import build_pipeline_summary, render_pipeline_scorecard, run_ah_relative_value_pipeline

    config = PipelineConfig(
        a_symbol=args.a_symbol,
        h_symbol=args.h_symbol,
        benchmark_symbol=args.benchmark,
        benchmark_market=args.benchmark_market,
        benchmark_mode=args.benchmark_mode,
        internal_benchmark_weighting=args.internal_benchmark_weighting,
        start_date=args.start_date,
        end_date=args.end_date,
        train_end_date=args.train_end_date,
        require_significant_cointegration=not args.allow_non_coint,
        same_issuer_check=args.same_issuer_check,
        data=DataConfig(
            data_provider=args.data_provider,
            a_csv_path=args.a_csv,
            h_csv_path=args.h_csv,
            fx_csv_path=args.fx_csv,
            benchmark_csv_path=args.benchmark_csv,
            constant_fx_rate=args.constant_fx_rate,
            share_ratio=args.share_ratio,
            tushare_token=args.tushare_token,
            tushare_ts_code_a=args.tushare_ts_code_a,
            tushare_ts_code_h=args.tushare_ts_code_h,
            tushare_adjust=args.tushare_adjust,
            simulation_seed=args.simulation_seed,
            simulation_n_days=args.simulation_n_days,
        ),
        strategy=StrategyConfig(
            entry_z_candidates=z_grid,
            exit_z=args.exit_z,
            stop_z=args.stop_z,
            z_window=args.z_window,
            z_min_periods=args.z_min_periods,
            max_holding_days=args.max_holding_days,
            position_size_fraction=args.position_size_fraction,
            initial_capital=args.initial_capital,
            objective=args.objective,
            execution_mode=args.execution_mode,
            execution_timing=args.execution_timing,
            entry_signal_mode=args.entry_signal_mode,
            hedge_ratio_mode=args.hedge_ratio_mode,
            return_filter_mode=args.return_filter_mode,
            cointegration_gate_mode=args.cointegration_gate_mode,
            ecm_gate_mode=args.ecm_gate_mode,
            half_life_anchor_mode=args.half_life_anchor_mode,
            half_life_z_window_multiplier=args.half_life_z_window_multiplier,
            half_life_max_holding_multiplier=args.half_life_max_holding_multiplier,
            return_filter_window=args.return_filter_window,
            return_filter_min_periods=args.return_filter_min_periods,
            adv_window=args.adv_window,
            adv_min_periods=args.adv_min_periods,
            max_adv_fraction=None if args.max_adv_fraction is not None and args.max_adv_fraction < 0 else args.max_adv_fraction,
            a_lot_size=args.a_lot_size,
            h_lot_size=args.h_lot_size,
            backtest_engine=args.backtest_engine,
            mean_reversion_gate_mode=args.mean_reversion_gate_mode,
            ou_window=args.ou_window,
            ou_det_order=args.ou_det_order,
            ou_k_ar_diff=args.ou_k_ar_diff,
            ou_lags=args.ou_lags,
            half_life_min_days=args.half_life_min_days,
            half_life_max_days=args.half_life_max_days,
            lb_p_value_min=args.lb_p_value_min,
            min_weight=args.min_weight,
            position_sizing_mode=args.position_sizing_mode,
            target_vol=args.target_vol,
            vol_window=args.vol_window,
            vol_min_periods=args.vol_min_periods,
            max_leverage=args.max_leverage,
            max_drawdown=args.max_drawdown,
            suspend_days=args.suspend_days,
            portfolio_max_drawdown=args.portfolio_max_drawdown,
            risk_free_rate=args.risk_free_rate,
        ),
        costs=CostConfig(
            a_buy_cost_bps=args.a_buy_cost_bps,
            a_sell_cost_bps=args.a_sell_cost_bps,
            h_buy_cost_bps=args.h_buy_cost_bps,
            h_sell_cost_bps=args.h_sell_cost_bps,
            h_stamp_duty_bps=args.h_stamp_duty_bps,
            fx_conversion_bps=args.fx_conversion_bps,
            a_slippage_bps=args.a_slippage_bps,
            h_slippage_bps=args.h_slippage_bps,
            a_impact_bps_per_100pct_adv=args.a_impact_bps_per_100pct_adv,
            h_impact_bps_per_100pct_adv=args.h_impact_bps_per_100pct_adv,
            a_short_borrow_apr_bps=args.a_short_borrow_apr_bps,
            h_short_borrow_apr_bps=args.h_short_borrow_apr_bps,
            a_long_financing_apr_bps=args.a_long_financing_apr_bps,
            h_long_financing_apr_bps=args.h_long_financing_apr_bps,
            base_cost_bps=args.base_cost_bps,
            impact_cost_bps=args.impact_cost_bps,
        ),
        rolling=RollingConfig(),
        cache_dir=None if args.no_cache else args.cache_dir,
        refresh_cache=args.refresh_cache,
        resume_from_cache=args.resume_from_cache,
        output_dir=args.output_dir,
    )

    result = run_ah_relative_value_pipeline(config)
    print(render_pipeline_scorecard(build_pipeline_summary(config, result)))
    return 0
